### ISSUE TITLE
run problem

### ISSUE THREAD

**Issue by JinHeap** [zchYellow/TransE#3]
-----Start evaluation-----
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    main()
  File "main.py", line 40, in main
    kge_model.launch_evaluation(session=sess)
  File "D:\Python\TransE\src\model.py", line 153, in launch_evaluation
    'out_queue': rank_result_queue}).start()
  File "D:\Python\Anaconda3\envs\tensorflow\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\Python\Anaconda3\envs\tensorflow\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Python\Anaconda3\envs\tensorflow\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Python\Anaconda3\envs\tensorflow\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Python\Anaconda3\envs\tensorflow\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
**TypeError: can't pickle _thread.lock objects**

(tensorflow) D:\Python\TransE\src>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Python\Anaconda3\envs\tensorflow\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\Python\Anaconda3\envs\tensorflow\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
**EOFError: Ran out of input**

sorry,I'm freshman.when used yuor code,I have problem as list.

**Comment by ZichaoHuang** [comment]
@JinHeap I think it is something about multiprocessing of python on Windows. The code has only been tested on Ubuntu, maybe try to run it on Ubuntu or other Linux distribution?

**Comment by JinHeap** [comment]
好的
