### ISSUE TITLE
multiprocessing里面的joinablequeue卡住

### ISSUE THREAD

**Issue by ocsponge** [zchYellow/TransE#9]
运行sh train_fb15k.sh会在model.py第168行 eval_result_queue.join() 卡住，但是运行sh train_wn18.sh.sh没有任何问题。人为ctrl+c结束会显示
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    main()
  File "main.py", line 40, in main
    kge_model.launch_evaluation(session=sess)
  File "/Users/shishang.zy/Desktop/Table/TransE-master/src/model.py", line 168, in launch_evaluation
    eval_result_queue.join()
  File "/anaconda3/lib/python3.6/multiprocessing/queues.py", line 305, in join
    self._cond.wait()
  File "/anaconda3/lib/python3.6/multiprocessing/synchronize.py", line 262, in wait
    return self._wait_semaphore.acquire(True, timeout)
KeyboardInterrupt

**Comment by ZichaoHuang** [comment]
请问卡住的时候（ctrl+c之前）有什么输出呢？最好能够提供一下命令行的截图。

**Comment by ocsponge** [comment]
ctrl+c之前没有错误, 就是卡住了, 打印了167行的'-----Joining all rank calculator-----'之后就没有输出了, 按道理应该会继续打印169行的'-----All rank calculation accomplished-----', 但是没有, 所以我才说卡住了, 我最长等过几个小时都没有运行到169行

**Comment by ocsponge** [comment]
我刚刚换到台式机试了一下发现可以正常运行,但是在mac上还是不行,会卡住

**Comment by ZichaoHuang** [comment]
这份代码只在Linux中测试过，如果是macOS或者Windows平台的TensorFlow的话，有可能会有其他的问题。

**Comment by ocsponge** [comment]
我怀疑就是单纯数据量大了导致队列queue卡住了, 因为我在mac上运行wn18是没问题的.
